- main/acle.md
> [main] Add reference to Cortex-M Security Extension (CMSE) specifications

- main/acle.md
- morello/morello.md
- mve_intrinsics/mve.md
- mve_intrinsics/mve.template.md
- neon_intrinsics/advsimd.md
- neon_intrinsics/advsimd.template.md
worry if you cannot run these scripts on your machine, your
patch will be automatically checked …
> Prepare 2021Q4 release

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/proposal.md
- .github/PULL_REQUEST_TEMPLATE.md
@DanielKristofKiss - this fixes #80.
> [community] Fix rendering of SPDX data in github templates.

- CONTRIBUTING.md
> [contributing] Update the CI section of the contributing guidelines.

- README.md
> [README] Update pointers to PDF and HTML versions.

- main/acle.md
---
---
a proposal](../CONTRIBUTING.md#proposals-for-new-content).
checklist.
PR (do not …
> Remove link text such as “sec-…” and “ssec-…”

- main/acle.md
---
---
a proposal](../CONTRIBUTING.md#proposals-for-new-content).
checklist.
PR (do not …
> [cleanup] Header-file related tweaks

- main/acle.md
> [main] Add description of support levels.

- CONTRIBUTING.md
> [community] Default behavior for allcontributors.

- main/acle.md
> Tech comm review for 2022Q1

- CONTRIBUTING.md
Issues were pointed out by https://github.com/stuij in
https://github.com/ARM-software/acle/pull/185 (commit
cac773dd7eb539968e67e78cfd805736ed1e17ef).
tricky to set up on non-*nix machines). The …
> [community] Fix branch descriptions in CONTRIBUTING.md.

- README.md
> [README] Add CMSE to the list of documents.

- main/acle.md
- main/design_documents/function-multi-versioning.md
> FunctionMultiVersioning updates

- main/acle.md
- main/design_documents/function-multi-versioning.md
> Fix external link to GCC docs and changelog sections

- .github/ISSUE_TEMPLATE/bug_report.md
> [bug report template] Remove default assignee.

- main/acle.md
- main/design_documents/function-multi-versioning.md
> [main] Fix wordings

- main/acle.md
- main/design_documents/function-multi-versioning.md
> [main] Fix wording

- main/acle.md
> [Release] Version 2022Q4 of the ACLE

- .all-contributorsrc
---
name: Update my name and profile URL in .all-contributersrc
about: Auxiliary documentation (contributors list).
---
As for any pull request, please make sure …
> Update my name and profile URL in .all-contributersrc

- main/acle.md
> Correct sme features names and registers.

- tools/howto-build-github-pages-locally.md
The GitHub pages are only built when a commit is added to the `latest-release` branch. This makes the process of testing the HTML rendering of local changes difficult.
This patch adds a new document which describes one process to build the GitHub page locally.
---
--- …
> Add a guide for building GitHub Pages locally

- README.md
All the known specifications have already been copied from Arm Developer site to GitHub, so this section is not relevant anymore.
---
---
a …
> Remove section "Transitioning the ACLE specifications"

- cmse/cmse.md
- main/acle.md
- neon_intrinsics/advsimd.md
- neon_intrinsics/advsimd.template.md
> [Release] 2023 Q2

- main/acle.md
> Set main/acle.md draftversion to true

- main/acle.md
> Fmv bti typo

- main/acle.md
> [FMV] Disallow duplication of features in mangled names.

- main/acle.md
> [NFC] Add missing Oxford comma

- .gitignore
---
---
Just extending the .gitignore file for those working on MacOS.
tricky to set up on …
> Add DS_Store to the git ignore.

- main/acle.md
This example was missed in previous change, needs to change as we no longer have the inferred default.
---
---
a proposal](https://github.com/ARM-software/acle/blob/main/CONTRIBUTING.md#pro …
> Update acle.md FMV example
