neon_intrinsics/advsimd.rst
neon_intrinsics/advsimd.template.rst
tools/intrinsic_db/advsimd.csv

Fixes #15: Advanced SIMD support is available if the __ARM_NEON macro is predefined, https://developer.arm.com/documentation/101028/0012/13--Advanced-SIMD--Neon--intrinsics.

[intrinsics] Use the `__ARM_NEON` macro for the Advanced SIMD support.

---

neon_intrinsics/advsimd.rst
neon_intrinsics/advsimd.template.rst
tools/intrinsic_db/advsimd.csv

Simular to the usdot intrinsics, these are all implementable on AArch32 using Dn/Dn+1 register pairs.

acle: Correct udot, sdot specification on AArch32

---

tools/requirements.txt

This PR is here to fix build failure caused by the deprecation of unauthenticated cloning of repositories in github: https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
tricky to set up on non-*nix …

[ci] Update cloning command for rst2pdf via pip.

---

tools/requirements.txt

This is a cherry pick of #97 into `main`.
According to [1], the unauthenticated access via ssh have been
deprecated in GitHub.
[1] https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
tricky to set …

[ci] Fix use of git clone command.

---

main/acle.rst

Just a few minor fixes for RST styling in acle.rst, plus trimming some trailing whitespace.

Fixup RST styling in acle.rst.

---

.all-contributorsrc
README.md

This is just updating `next-release` with the context of `main` that does not land first in `next-release`, namely the patches that the @allcontributors bot creates.

Merge `main` into `next-release`. 

---

main/acle.md
main/design_documents/ARM_NEON_SVE_BRIDGE.md

Adds section 1.11.1 NEON-SVE Bridge which details the addition of
svextract_ and svinsert_

Add NEON-SVE Bridge

---

main/acle.md
morello/morello.md
mve_intrinsics/mve.md
mve_intrinsics/mve.template.md
neon_intrinsics/advsimd.md
neon_intrinsics/advsimd.template.md

1. Set release number
2. Fix sectioning of the Morello specifications. 
worry if you cannot run …

[2021Q4] Set release numbers for 2021Q4

---

main/acle.md
main/design_documents/__ARM_FEATURE_MOPS.md

The execution of the `__arm_mops_memset_tag` introduced for the
Armv8.8-A/v9.3-A MOPS extension also requires the MTE extension to be
available.
This patch updates its description on the ACLE to require both
`__ARM_FEATURE_MOPS` and `__ARM_FEATURE_MEMORY_TAGGING` feature macros.
This fixes #160

Require for MTE the __arm_mops_memset_tag intrinsic

---

main/acle.md

a proposal](../CONTRIBUTING.md#proposals-for-new-content).
checklist.
of any file I have edited. Format is …

[cleanup] Move punctuation outside `…`

---

main/acle.md

The “Future directions” chapter was previously the last chapter
of the document, but due to later additions, it's now in the
middle of extension-specific chapters.  This patch moves it
back to the end and adds a comment.
---
---
a …

[cleanup] Move “Future directions” chapter to the end

---

.github/workflows/ci.yml

The markdown checker wasn't picking up the json file due
to a typo in the filename.
---
---
a proposal](../CONTRIBUTING.md#proposals-for-new-content).
As for any pull request, please make sure to go …

[ci] Fix filename in ci.yml

---

.github/PULL_REQUEST_TEMPLATE.md

1. Fix typo.
2. Add a checkbox on how to list the changes in the changelog.
3. Require to check the PDF output on content/style changes.
Fixes #165 
tricky to set up on non-*nix machines). The …

[community] Improve PR template text.

---

main/acle.md
main/design_documents/function-multi-versioning.md

Function Multi Versioning provides a convenient way to select the most
appropriate version of a function in runtime.
AArch32 features to be added later.

Add Function Multi Versioning.

---

.github/PULL_REQUEST_TEMPLATE.md

We ask contributors to explicitly state if they don't want to get
added to the list of contributors, which shows up at https://github.com/ARM-software/acle#contributors-
tricky to set up on …

[community] Checkbox for list of contributors.

---

main/design_documents/pacbti-tfm.rst

This patch renames pacbti-m-tfm.rst to make it non limited to the cortex-m scope and improves one example related to PAC extension target feature macros. …

[ACLE] Improve PAC extension target feature macros example.

---

main/acle.md

In the Q2 2018 version of the document, __ARM_FEATURE_CRYPTO was
deprecated in favor of finer-grained __ARM_FEATURE_AES,
__ARM_FEATURE_SHA2 and __ARM_FEATURE_SHA512 flags. But the ARM
cryptography extension originally covered four features: FEAT_AES,
FEAT_PMULL, FEAT_SHA1, and FEAT_SHA256.
This has generated some confusion, as for example it was not clear if
FEAT_PMULL was included under __ARM_FEATURE_AES.
Specifically, the ArmArm [1], issue G.b released on 22 July 2021, on
page A2-72 says:
The AES functionality, including support for multiplication of
64-bit polynomials. The ID_AA64ISAR0_EL1.AES field indicates
whether this functionality is supported.
This means that FEAT_AES and FEAT_PMULL need to be paired together in
an implementation.
[1] …

[main] Improve the description of the cryptographic extensions.

---

main/acle.md
main/design_documents/aarch64_sve_pcs.md

Add documentation for the aarch64_sve_pcs attribute, which allows manual
enforcement of the SVE procedure call standard on functions …

Add documentation for aarch64_sve_pcs attribute

---

main/acle.md

The cover note for the original SVE patch said:
For now the instruction-to-intrinsic table includes only the
FEAT_SVE instructions.  A later patch will add the rest.
This patch does that.  It also tightens some existing intrinsic
links to exclude unrelated functions.  For example, linking to
svcvt_ excludes svcvtlb and svcvtlt.
The patch doesn't add an entry to the changelog since it is
really just completing the existing SVE work, which is already
listed as a change in the next release.
---
---
We are …

[main] Add instructions for SVE extensions

---

main/acle.md

For this release only the main ACLE specifications have changed. …

[Release] Version 2022Q2 of the ACLE.

---

main/acle.md

Previously, all the references to the section `<arm_sve.h>` were
missed in the web version of the specs because Jenkins was generating
the anchor as `arm_sveh` instead of `arm_sve.h`.
tricky to set …

[main] Fix anchor for arm_sve.h.

---

main/acle.md

[main] Add Alpha support for SME

---

main/acle.md

To guard usage of C/C++ operators on sizeless SVE vectors, we should
expand __ARM_FEATURE_SVE_VECTOR_OPERATORS to include sizeless vectors
and __ARM_FEATURE_SVE_PREDICATE_OPERATORS to include predicate vectors.
It's possible that we also need something in the spec to explain what
these operators do, but right now I would like to get consensus on
what the feature macro should look like so we can add it to clang and
gcc before people start using the operators without it.
---
---
We are looking forward to …

[main] expand SVE_VECTOR_OPERATORS to include sizeless vectors

---

main/acle.md

To guard the usage of Load-AcquirePC instructions in inline assembly, https://reviews.llvm.org/D127798 introduces macro __ARM_FEATURE_RCPC in Clang/LLVM.
This patch documents the existence of the feature MACRO, its availability and use case.
format …

[main] Add feature macro __ARM_FEATURE_RCPC

---

main/acle.md

While implementing the SME ACLE for GCC, I noticed that svwrite was inconsistent with svadd* and with the MOP intrinsics.  svwrite (which maps to MOVA) had an _m suffix, to reflect the /M on the assembly predicate operands, but the other functions didn't.
We could resolve the inconsistency in either direction: remove _m from svwrite or add it to the other intrinsics. Although I don't have a strong preference, adding the _m to the other intrinsics seems more future proof.  SME2 adds various unpredicated intrinsics and there's a risk of a future name clash if we don't establish a distinction between /m functions and unpredicated functions.  Making _m explicit also seems more consistent with SVE.
---
about: Technical issues, document format problems, bugs in scripts or …

[main] Add an _m suffix to some SME intrinsics

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/proposal.md
.github/PULL_REQUEST_TEMPLATE.md

GitHub does not work correctly with relative links in PR and issue templates. Because of this, wrong links are generated in Pull Requests and Issues (i.e. error 404).
As far as I could find, there is no other solution besides changing them to absolute links. This is unfortunate because we now link directly to GitHub pages, but it's better than showing error 404 to contributors.
---
---
make it part of the Arm C Language Extension …

docs: use GitHub absolute links in PR and issue templates

---

main/acle.md

This patch moves changes that have been made since the 2022Q2 release to a new changelog section.  It also fixes a typo/ missed change in __ARM_FEATURE_SVE_PREDICATE_OPERATORS and clarifies that SME immediate operands must be in the range of the underlying instructions.
---
--- …

[main] Some minor corrections

---

main/acle.md

Arm v8.9-a/v9.4-a has allocated the encoding 0b11 in PRFM's `Rt<2:1>` field (which represents the cache level targetted by the prefetch instruction) the name "SLC", to represent prefetches to the system-level cache. In some documents this is called FEAT_PRFMSLC.
This change updates the ACLE intrinsics to match what is available in the PRFM instructions.
--- …

Add SLC as a valid Prefetch Target

---

main/acle.md

Arm v9.4-a introduces 128-bit system registers (FEAT_SYSREG128), which are accessed using the `MSRR` and `MRRS` instructions. This change adds intrinsics for these instructions, in line with the existing intrinsics we have for other system register accesses.
---
rendered in the PDF and other output format …

Add Intrinsics for 128-bit System Registers

---

main/acle.md

Some changes that did not make into the 2022Q4 release were erroneously listed as being part of it on trunk. That is, the changelog is correct in the release itself, but not on trunk.
This patch fixes it.
---
---
guidelines](https://github.com/ARM-software/acle/blob/main/CONTRIBUTING.md), in particular …

Fix changes for next release

---

main/acle.md

Correct FMV compiler options typo (-fpendantic => -pedantic)

---

cmse/README.md

Bug fix for #247.
The broken link is caused by the newline in the middle of the link syntax in Markdown.
This patch removes newlines within Markdown links.
---
---
a …

Fix broken link in CMSE html page

---

CONTRIBUTING.md
LICENSE.md
README.md
tools/LICENSE.md
tools/acle_template.tex

One of the files under the tools directory is under the BSD 3-Clause license, but this fact is not clear in our licensing descriptions. This has been fixed.
Additionally, a copy of the BSD 3-Clause is included in the project in order to abide by its requirements.
This patch also fixes some related typos and changes all instances of "licence" to the US English spelling.
---
---
make it part of the Arm C Language Extension (ACLE) …

Clarify licensing information

---

cmse/cmse.md
main/acle.md

The section "Arguments on the stack and floating point handling" contains an incorrect remark about its example code sequence.
It states that clearing FP registers only if they contain Secure information is an optimisation in the sense that it can be done regardless. This is wrong since the clearing must not be done if they don't have Secure information. Otherwise an unnecessary FP context would be created, which could have serious side effects such as the raise of UsageFault.
This patch removes the incorrect text.
---
---
If this PR …

Remove incorrect optimisation remark in CMSE's floating-point register clearing

---

cmse/cmse.md
main/acle.md

In CMSE section 8.4.2, the example states that some code sequence that clears FP registers is relevant due to the "soft float ABI".  This is wrong because FP registers aren't available in the soft float ABI to begin with.
This patch removes the mention to soft float ABI.
---
--- …

Remove incorrect information about the floating-point ABI used in CMSE's Arguments on the stack and floating point handling

---

cmse/cmse.md
main/acle.md

The original description and example incorrectly showed that a non-secure function pointer must be cast into a regular function pointer if the target function wasn't non-secure. This is incorrect because the corresponding call instruction, BLXNS, is able to handle calls that don't involve security state transitions. In other words, it supports target functions that are either secure or non-secure.
This patch corrects the description and the example, and emphasizes that telling apart secure and non-secure target functions in code is simply a matter of optimisation and is not required.
---
---
Please use the …

Correct description and example in CMSE's Non-secure function pointers

---

main/acle.md

guidelines](https://github.com/ARM-software/acle/blob/main/CONTRIBUTING.md#continuous-integration). Don't …

Add support for FEAT_LRCPC3

---

main/acle.md

Require arm_new_za to set ZA to zero

---

main/acle.md

Previously the (alpha) SME intrinsics were documented to take two slice parameters: a 32-bit variable index and a 64-bit constant offset.  However, it isn't very C-like to split an addition in this way, and as Sander points out, it isn't really consistent with the way that we handle vnum parameters.
---
---
We would like to encourage you reading through the …

[main] Combine SME slice parameters

---

main/acle.md

Use keywords for SME attributes

---

main/acle.md

Add missing word to Function Multiversioning's Name Mangling section

---

main/acle.md

Change-Id: Iba0e37d8b12debe34edae3bb8350bb1ef80a616a
---
---
Please use the proposal …

Describe reinterpret intrinsics for vector and vector tuple types

---

main/acle.md

This patch makes a few tweaks to the SME2 intrinsics:
*   The type suffix of the SME2 svread* intrinsics needs to be
explicit (non-optional), since there is no merge input that
can be used to infer it.
*   The zn argument to the svluti* intrinsics is a collection of
2-bit and 4-bit quantities, so it doesn't have a natural element
size or signedness.  It seems better to keep it as svuint8_t for
all variants.
*   Because of that, there is no argument that implies the return
type of the svluti* intrinsics, so the type suffix needs to be
explicit.  Also, since the instruction performs a bag-of-bits
lookup, it makes sense to have floating-point variants too.
*   The ZA slice forms of svread* and svwrite* are likewise
bag-of-bits moves, so we can provide alternatives for all
element types.
* …

Tweaks to the SME2 intrinsics

---

main/acle.md

---
---
Let's add MOPS to FMV. Intentionally and speculatively left some space between MOPS and SME2.
format is the same described in the …

[FMV] Adding MOPS

---

tools/build-github-pages.sh

Recent updates to the pages-gem repository, used by the build-github-pages CI job, have introduced a regression by which the build fails due to incompatible Ruby version.
We'll fix this by passing in a specific Ruby version that's compatible.
---
--- …

[CI] Fix build-github-pages CI job

---

tools/acle_template.tex

In the existing setup, the *.md source files are converted to PDF by pandoc that invokes pdflatex internally. With the default font encoding, underscore characters inside paragraphs of text look like whitespace (or absent) in the produced PDF documents w.r.t. copy-pasting text from PDF viewer or searching. This may confuse users as it makes `__ARM_FEATURE_name` and `long_function_name` strings invisible to the "Search ..." function of a viewer, but only if they are not inside a standalone block of code.
One of the solutions is to use T1 font encoding and ensure that Type 1 fonts are available (i.e. pdflatex does not have to use rasterized Type 3 fonts).
Fixes #282.
---
---
**Thank …

[PDF] Fix searching and copy-pasting underscore characters

---

main/acle.md

The vertical bar is interpreted as a table column separator by the HTML generator. Escaping the bar fixes the issue.
---
---
a proposal](https://github.com/ARM-software/acle/blob/main/CONTR …

Escape vertical bar for proper rendering in HTML

---

main/acle.md

The Armv9.5a introduces the FEAT_PAuth_LR extension, adding an enhancement
to the Pointer Authentication extension where the value of PC is used as
a diversifier when signing pointers.
This updates the ACLE to support the extension by the introduction of a
new feature macro and the addition of a new possible value to the
existing `__ARM_FEATURE_PAC_DEFAULT` macro.

Add ACLE macros for FEAT_PAuth_LR

---

main/acle.md

[FMV] Adjust features priorities and add alternative names.

---

main/acle.md

The zn arguments to the svluti* intrinsics contain 4-bit indices. We'd decided to use svuint8_t for all such arguments, but a typo in svluti4_lane_zt_s16_x4 meant that it used svuint16_t instead.
Both Clang and GCC implement the patched behaviour.
---
--- …

Fix the argument type of svluti4_lane_zt_s16_x4

---

main/acle.md

The SME and SME2 ACLE have been implemented in upstream GCC and Clang/LLVM, so I think they're ready to be treated as Beta.
---
---
a …

Promote the SME(2) ACLE status from Alpha to Beta

---

main/acle.md

The ACLE defines a feature macro called __ARM_ACLE:
__ARM_ACLE is defined to the version of this specification implemented, as 100 * major_version + minor_version. An implementation implementing version 2.1 of the ACLE specification will define __ARM_ACLE as 201.
However, a long time ago, we changed the versioning scheme of the ACLE from "major.minor" to a combination of year and quarter. For instance the latest release is 2023 Q2.
Since the macro's definition is now out of date, we now move to a new scheme:
`__ARM_ACLE` is defined to the version of this specification implemented, formatted as `{YEAR}{QUARTER}{PATCH}`.
The value would be the integer formed by the year (4 digits) concatenated to the quarter's number (1 digit), finally concatenated to the patch release (1 digit). So the …

Define new value for the __ARM_ACLE macro

---

main/acle.md

This decouples feature priorities from name mangling. Doing so will prevent ABI breakages in case we change the feature priorities.
---
---
a …

[FMV] Use lexicographic order of feature names when mangling.

---

main/acle.md

Update the release notes for Function Multi Versioning.

---

main/acle.md

The default version's name to be mangled to avoid problems with ifuncs due to the ifunc to be called as the base name of the function.
checklist.
format is the same described in the …

[FMV] Change the default versions name mangling.

---

main/acle.md

Implements #297. 
This could be more valuable in cooperation with #301. …

Introduce __ARM_ACLE_VERSION macro.

---

main/acle.md

The combination of these attributes is now permitted. Therefore, it is
also worth clarifying the existance of a single default version across
all translation units with the explicitly provided version being the
preferred in case `target_version` and `target_clones` are mixed.
---
--- …

[FMV] Allow mixing target_version with target_clones.

---

main/acle.md

Address pre-release review feedback

---

main/acle.md

Address textual issues raised

---

main/acle.md

Set 2024Q1 version numbers in changelogs and document headers

---

main/acle.md

Add message of Alpha state for SVE2.1

---

cmse/cmse.md
main/acle.md

This addresses the vulnerability described in CVE-2024-0151.
Patch by Victor Campos.
Co-authored-by: Victor Campos <victor.campos@arm.com>

Add new requirements to code generation of CMSE Entry function and Non-secure calls

---

main/acle.md

Some features are later versions of others, like sve2 and sve,
therefore performing equality checks on system register values
would incur incorrect feature detection on later hardware. See
https://github.com/ARM-software/acle/issues/320 for example.
Therefore we should instead do >= comparisons when HWCAP info
is not available.
I am also fixing incorrect detection for LSE and WFxT. Lastly to
detect SVE2 and SME2 I am using the SVEVer and SMEVer bitfields
respectively.
----
---
We are looking forward to …

[FMV] Fix incorrect system register dependencies.

---

.github/workflows/ci.yml

The draftversion checker must run only in the main branch. This patch limits the run conditions to abide by this.

Limit the run of draftversion-check to the relevant branches

---

main/acle.md

ACLE had developed a style of prefixing empty <span>s with:
However, this appears to confuse the GitHub renderer when used in bullet points.  It was skipping large portions of text after the streaming-intrinsic and vl-dependent anchors, and formatting later text as though it was part of the same bullet point.
Also, I think these large comments make it harder to see the <span> itself.  Probably because of this,
16-bit-floating-point-data-processing-operations
had become unmoored from the associated text.
This patch removes the comments (which seems to fix the rendering) and moves 16-bit-floating-point-data-processing-operations to the appropriate place.  I checked each anchor manually to make sure that it still worked.
---
about: Technical issues, document format …

Remove comments before <span>s

---

main/acle.md

guidelines](https://github.com/ARM-software/acle/blob/main/CONTRIBUTING.md#continuous-integration). Don't …

[FMV] Add __FUNCTION_MULTI_VERSIONING_SUPPORT_LEVEL.

---

main/acle.md

Add Alpha support for SME2.1

---

main/acle.md

In one instance, it was incorrectly named `__ARM_FEATURE_SVE2.1`.

Fix incorrect naming of __ARM_FEATURE_SVE2p1

---

main/acle.md

Fix formatting error cause by #321

---

main/acle.md

According to ArmARM:
SHA2, bits [15:12]
0b0000 No SHA2 instructions implemented.
FEAT_SHA256 implements the functionality identified by the value 0b0001. If the value of ID_AA64ISAR0_EL1.SHA1 is 0b0000, this field must have the value 0b0000.
SHA1, bits [11:8]
0b0000 No SHA1 instructions implemented.
FEAT_SHA1 implements the functionality identified by the value 0b0001. If the value of ID_AA64ISAR0_EL1.SHA2 is 0b0000, this field must have the value 0b0000.
To my understanding this means you can't have one without the other.
---
---
If …

[FMV] Unify sha1, sha2.

---

.github/workflows/ci.yml

Action 'upload-artifact' version 2 has been deprecated, hence the need to update its version.
To piggyback on this work, this patch updates all GitHub Action versions to their latest release.

Update GitHub Action versions

---

main/acle.md

As originally discussed in #315 and then in #329 we want to unify features that the toolchains cannot support independently. In the case of ls64 I have attempted to split the lumped feature in the compiler (see https://github.com/llvm/llvm-project/pull/101712), but unfortunately this would break backwards compatibility:
Mapping 'ls64' to FeatureLS64_ACCDATA would enable all three of {FeatureLS64, FeatureLS64_V, FeatureLS64_ACCDATA} but then using 'nols64' either on the command line or the assembler directive would only disable FeatureLS64_ACCDATA without disabling the other two. For that we would have to map 'ls64' to FeatureLS64, but then it would not enable the other two.
As far as I am aware there are no hardware implementations out there which implement ls64 without ls64_v or …

[FMV] Unify ls64, ls64_v and ls64_accdata.

---

main/acle.md

Minor change in the FMV table to improve readability.
---
---
Please use the proposal …

[FMV][AArch64] Add missing whitespace between comma separated features.

---

main/acle.md

According to https://developer.arm.com/documentation/102105/latest Arm Architecture Reference Manual for A-profile architecture: Known issues
2.206 D22789
In section C5.2.25 "SSBS, Speculative Store Bypass Safe", under the heading 'Configurations', the text that reads:
"This register is present only when FEAT_SSBS is implemented.
Otherwise, direct accesses to SSBS are UNDEFINED."
is changed to read:
"This register is present only when FEAT_SSBS2 is implemented.
Otherwise, direct accesses to SSBS are UNDEFINED."
This suggests that it's not worth splitting FEAT_SSBS2 from FEAT_SSBS in the compiler, since FEAT_SSBS cannot be used for predicating the MRS/MSR instructions. Those can access PSTATE.SSBS only when FEAT_SSBS2 is available. Moreover, there are no hardware implementations which …

[FMV] Unify ssbs and ssbs2.

---

main/acle.md

If we split these features in the compiler (see relevant pull request https://github.com/llvm/llvm-project/pull/109299), we would only be able to hand-write a 'memtag2' version using inline assembly since the compiler cannot generate the instructions that become available with FEAT_MTE2. On top of that these instructions only work at Exception Level 1, so they would be unusable since FMV is a user space facility. I am therefore unifying them in the ACLE specification.
---
---
We are looking forward to …

[FMV] Unify memtag and memtag2.

---

main/acle.md

I originally tried splitting these features (see relevant pull request https://github.com/llvm/llvm-project/pull/110816), but the following came to my attention:
According to https://developer.arm.com/documentation/ddi0487/latest Arm Architecture Reference Manual for A-profile architecture:
D23.2.83 ID_AA64ZFR0_EL1, SVE Feature ID Register 0
ID_AA64ZFR0_EL1.AES, bits [7:4]
> FEAT_SVE_AES implements the functionality identified by the value 0b0001.
> FEAT_SVE_PMULL128 implements the functionality identified by the value 0b0010.
> The permitted values are 0b0000 and 0b0010.
Andrew Carlotti suggests that the same applies for ID_AA64ISAR0_EL1.AES (https://github.com/llvm/llvm-project/pull/110816#issuecomment-2388410290)
D19.2.61 ID_AA64ISAR0_EL1, AArch64 Instruction Set Attribute Register 0 …

[FMV] Unify aes with pmull and sve2-aes with sve2-pmull128.

---

main/acle.md

Feature `rpres` allows an increase in the precision of the single-precision
floating-point reciprocal estimate and reciprocal square root estimate
from an 8-bit mantissa to a 12-bit mantissa depending on the value FPCR.AH
of the Floating-point Control Register.
Similarly, `ebf16` allows existing floating-point instructions (BFDOT, BFMMLA,
BFMOPA, BFMOPS, and BFVDOT) to change numeric behaviour depending on the
value FPCR.EBF of the Floating-point Control Register.
Feature `memtag3` allows Tag Check Faults to change behaviour depending on
the value SCTLR_ELx.{TCF, TCF0} of the System Control Register.
The runtime detection in FMV does not examine the content of control
registers, therefore runtime dispatch cannot be based on that. One may
argue there is value in altering the control …

[FMV][AArch64] Remove features which expose non exploitable runtime behavior.

---

main/acle.md

The FCVTNB instruction overwrites all bits of the destination register, thus passing an initial register argument is not required.
---
---
a …

Remove unnecessary argument from svcvtnb_mf8[_f32_x2]_fpm

---

main/acle.md

This change extends the name mangling of types to include the SME streaming
and ZA interface. This will avoid naming conflicts which can currently arise such
as in the following example:
```
void foo(void (*f)()) { f(); }
void foo(void (*f)() __arm_streaming) { f(); }
```
Without this change, both functions 'foo' above will mangle to the same
name, despite the function pointers being different.
---
---
make it part of the Arm C …

Include SME attributes in the name mangling of types

---

main/acle.md

The DGH instruction belongs to the hint space. It executes as NOP if the corresponding feature is not present in hardware, so there's no need for runtime dispatch.
---
---
a …

[FMV][AArch64] Remove feature dgh since it can be used unconditionally.

---

main/acle.md

All of sve-bf16, sve-ebf16, and sve-i8mm are obsolete. This is already reflected on the second column of the FMV table (we have bf16, ebf16, and i8mm with the same Architecture name).
According to https://developer.arm.com/documentation/ddi0487/latest Arm Architecture Reference Manual for A-profile architecture:
D23.2.72 ID_AA64ISAR1_EL1, AArch64 Instruction Set Attribute Register 1
ID_AA64ISAR1_EL1.I8MM, bits [55:52]
> When Advanced SIMD and SVE are both implemented, this field must return
> the same value as ID_AA64ZFR0_EL1.I8MM
ID_AA64ISAR1_EL1.BF16, bits [47:44]
> When FEAT_SVE or FEAT_SME is implemented, this field must return the
> same value as ID_AA64ZFR0_EL1.BF16.
So one could write target_version("sve+bf16") or sme+bf16 instead.
There is a proposal to explicitely document FMV …

[FMV] Remove features which can be expressed as a combination of other features

---

main/acle.md

[FMV] Document feature dependencies and detect at selection.

---

main/acle.md

The pre-SVE2p1 gather and scatter intrinsics allow vector displacements (offsets or indices) to be either signed or unsigned.  svld1q and svst1q instead required them to be unsigned.  This patch adds signed versions too, for consistency.
Also, the SVE2p1 stores were specified to take pointers to const, but they ought to be pointers to non-const instead.
---
---
We …

Some tweaks to the SVE2p1 load and store intrinsics

---

main/acle.md

Hi all,
While attempting to implement FMV in the GCC front-end some questions were raised that I think are worth clarifying here.
This PR changes the rules to use the default function to determine the signature and scope of the versioned function set.
This clears up some cases such as:
```C
int fn (int c = 1);
int __attribute__((target_version("sve"))) fn (int c = 2);
int bar() { return fn(); }
```
Where there are conflicting signatures and which default should be used is not clear at the moment.
```C
int fn (int c[]);
int __attribute__((target_version("default"))) fn (int c[1]) {
}
int __attribute__((target_version("sve"))) fn (int c[2]) {
}
```
Where if this should be considered a conflicting signature is not clear.
```C
int __attribute__((target_version("default"))) fn (int x) {
return …
```

Minor modification to FMV rules for scope and signatures

---

main/acle.md

The existing version selection rules are unclear, underspecified, and result in unintuitive version orderings.  Replace this with a simpler explicit selection algorithm.
---
---
a …

Simplify FMV version selection rules

---

main/acle.md

The SME2.1 and SVE2.1 ACLE have been implemented in upstream GCC and Clang/LLVM, so I think they're ready to be treated as Beta.
---
---
a …

Promote SME2.1 and SVE2.1 ACLE status from Alpha to Beta

---

main/acle.md

Clarify this rule in the document.
---
---
As for any …

[FMV] A depended-on feature must be of lower priority than the dependant.

---

main/acle.md

The base SVE forms of svdot have synthetic _n forms. The SVE2p1 and SME2 forms should too, for consistency.
---
---
a proposal](https://github.com/ARM-software/acle/blob/main/CONTRIBUTING.m …

Add _n forms of the SVE2p1 and SME2 svdot intrinsics

---

main/acle.md

Specify that GCS is at Beta level

---

main/acle.md

These cannot be detected by reading the ID_AA64ISAR1_EL1 register since their corresponding bitfields are hidden according to the Linux Kernel docs:
https://www.kernel.org/doc/html/latest/arch/arm64/cpu-feature-registers.html
Additionally the instructions that these features enable are unusable from user space (Exception Level 0).
For SPECRES the Arm Architecture Reference Manual says:
In AArch64 state, EL0 access to the System instructions is controlled by:
* When HCR_EL2.{E2H, TGE} is not {1, 1}, SCTLR_EL1.EnRCTX.
* When HCR_EL2.{E2H, TGE} == {1, 1}, SCTLR_EL2.EnRCTX.
For LS64 it says:
* SCTLR_EL1.EnALS, bit [56] : When FEAT_LS64 is implemented: When the Effective value of HCR_EL2.{E2H, TGE} is not {1, 1}, traps execution of an LD64B or ST64B instruction at EL0 to EL1.
* …

[FMV] Remove features predres and ls64.

---

main/acle.md

Add intrinsics for FEAT_SME_MOP4

---

main/acle.md

Allows function versions which make use of the Common Short Sequence
Compression instructions. Its entry is appended after MOPS to indicate
higher priority. The request was raised here:
https://github.com/llvm/llvm-project/issues/131218

[FMV] Add feature CSSC.

---

main/acle.md

Added feature macro for FEAT_SSVE_FEXPA

---

main/acle.md

Fix incorrect tmop fp8 definition and formatting of tmop and mop4 intrinsics

---

main/acle.md

Add a description for the "__ARM_FEATURE_CSSC" macro which checks for hardware support of CSSC instructions.
---
---
a proposal](https://github.com/ARM-software/acle/blob/main/CONTRIBUTING. …

Describe FEAT_CSSC test macro
